# Generated by Django 5.1.7 on 2025-03-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0002_campaign_status"),
        ("product", "0002_alter_product_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="products",
        ),
        migrations.AddField(
            model_name="campaign",
            name="products",
            field=models.ManyToManyField(
                related_name="campaigns", to="product.product"
            ),
        ),
    ]
