# Generated by Django 5.1.7 on 2025-05-24 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0003_remove_campaign_products_campaign_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="emails_per_hour",
            field=models.IntegerField(
                default=10, help_text="Maximum number of emails to send per hour"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_end_time",
            field=models.TimeField(
                default=datetime.time(22, 0),
                help_text="Daily end time for sending emails",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="send_start_time",
            field=models.TimeField(
                default=datetime.time(18, 0),
                help_text="Daily start time for sending emails",
            ),
        ),
    ]
