# Generated by Django 4.1.7 on 2025-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_lead_reference'),
        ('campaign', '0003_remove_campaign_products_campaign_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='leads',
            field=models.ManyToManyField(related_name='campaigns', to='dashboard.lead'),
        ),
    ]
