# Generated by Django 5.1.7 on 2025-03-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("physical", "Physical"),
                    ("digital", "Digital"),
                    ("service", "Service"),
                    ("subscription", "Subscription"),
                    ("bundle", "Bundle"),
                ],
                default="physical",
                max_length=20,
            ),
        ),
    ]
