# Generated by Django 5.1.7 on 2025-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_rename_leads_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="reference",
            field=models.CharField(default=2, max_length=5000),
            preserve_default=False,
        ),
    ]
