# Generated by Django 5.1.7 on 2025-03-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="is_active",
        ),
        migrations.AddField(
            model_name="agent",
            name="company",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
