# Generated by Django 5.1.7 on 2025-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0002_remove_agent_is_active_agent_company_agent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="systemPrompt",
            field=models.TextField(null=True),
        ),
    ]
