# Generated by Django 5.1.7 on 2025-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent", "0003_agent_systemprompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="signature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
